#!/usr/bin/env node

/**
 * Retrospect MCP Interactive Setup Wizard
 *
 * Guides the user through configuring all required and optional
 * integrations, then writes .env and updates claude_desktop_config.json.
 */

import readline from 'readline/promises';
import { existsSync, writeFileSync, readFileSync, readdirSync, mkdirSync } from 'fs';
import { homedir } from 'os';
import { join, resolve } from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// ─── ANSI helpers ────────────────────────────────────────────────────────────
const c = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  cyan: '\x1b[36m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
};

const bold = (s: string) => `${c.bold}${s}${c.reset}`;
const dim = (s: string) => `${c.dim}${s}${c.reset}`;
const green = (s: string) => `${c.green}${s}${c.reset}`;
const cyan = (s: string) => `${c.cyan}${s}${c.reset}`;
const yellow = (s: string) => `${c.yellow}${s}${c.reset}`;
const red = (s: string) => `${c.red}${s}${c.reset}`;

function printHeader() {
  console.log('');
  console.log(bold(cyan('  ╔══════════════════════════════════════╗')));
  console.log(bold(cyan('  ║      Retrospect MCP Setup Wizard     ║')));
  console.log(bold(cyan('  ╚══════════════════════════════════════╝')));
  console.log('');
  console.log('  매일 쓸 개발 로그 + 인사이트 + SNS 발행 도구를 설정합니다.');
  console.log('');
}

function printStep(n: number, total: number, title: string) {
  console.log('');
  console.log(bold(`  [${n}/${total}] ${title}`));
  console.log('  ' + '─'.repeat(40));
}

function ok(msg: string) {
  console.log(`  ${green('✓')} ${msg}`);
}

function warn(msg: string) {
  console.log(`  ${yellow('!')} ${msg}`);
}

function info(msg: string) {
  console.log(`  ${dim(msg)}`);
}

// ─── Browser opener ───────────────────────────────────────────────────────────
async function openBrowser(url: string): Promise<void> {
  try {
    await execAsync(`open "${url}"`);
  } catch {
    // silently ignore
  }
}

// ─── Obsidian vault detection ────────────────────────────────────────────────
function detectObsidianVaults(): string[] {
  const home = homedir();
  const candidates: string[] = [
    join(home, 'Documents'),
    join(home, 'Library', 'Mobile Documents', 'iCloud~md~obsidian', 'Documents'),
    join(home, 'Obsidian'),
    join(home, 'Desktop'),
  ];

  const vaults: string[] = [];

  for (const dir of candidates) {
    if (!existsSync(dir)) continue;
    try {
      const entries = readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        if (!entry.isDirectory()) continue;
        const vaultPath = join(dir, entry.name);
        if (existsSync(join(vaultPath, '.obsidian'))) {
          vaults.push(vaultPath);
        }
      }
    } catch {
      // skip unreadable dirs
    }
  }

  return vaults;
}

// ─── Masked input for API keys ───────────────────────────────────────────────
function maskKey(key: string): string {
  if (key.length <= 8) return '****';
  return key.slice(0, 6) + '****' + key.slice(-4);
}

// ─── .env writer ─────────────────────────────────────────────────────────────
interface EnvValues {
  CLAUDE_API_KEY: string;
  OBSIDIAN_VAULT_PATH: string;
  DATABASE_PATH: string;
  DEFAULT_GIT_REPO_PATH: string;
  NOTION_TOKEN?: string;
  NOTION_PARENT_PAGE_ID?: string;
  TWITTER_BEARER_TOKEN?: string;
  TWITTER_API_KEY?: string;
  TWITTER_API_SECRET?: string;
  TWITTER_ACCESS_TOKEN?: string;
  TWITTER_ACCESS_SECRET?: string;
  LINKEDIN_ACCESS_TOKEN?: string;
  LINKEDIN_USER_ID?: string;
  MEDIUM_TOKEN?: string;
}

function writeEnvFile(values: EnvValues, envPath: string) {
  const lines: string[] = [
    '# Retrospect MCP — generated by setup wizard',
    '',
    '# Claude AI (required)',
    `CLAUDE_API_KEY=${values.CLAUDE_API_KEY}`,
    '',
    '# Obsidian (required)',
    `OBSIDIAN_VAULT_PATH=${values.OBSIDIAN_VAULT_PATH}`,
    '',
    '# Database',
    `DATABASE_PATH=${values.DATABASE_PATH}`,
    '',
    '# Git',
    `DEFAULT_GIT_REPO_PATH=${values.DEFAULT_GIT_REPO_PATH}`,
  ];

  if (values.NOTION_TOKEN) {
    lines.push('', '# Notion');
    lines.push(`NOTION_TOKEN=${values.NOTION_TOKEN}`);
    lines.push(`NOTION_PARENT_PAGE_ID=${values.NOTION_PARENT_PAGE_ID ?? ''}`);
  }

  if (values.TWITTER_BEARER_TOKEN) {
    lines.push('', '# Twitter/X (Threads)');
    lines.push(`TWITTER_BEARER_TOKEN=${values.TWITTER_BEARER_TOKEN}`);
    lines.push(`TWITTER_API_KEY=${values.TWITTER_API_KEY ?? ''}`);
    lines.push(`TWITTER_API_SECRET=${values.TWITTER_API_SECRET ?? ''}`);
    lines.push(`TWITTER_ACCESS_TOKEN=${values.TWITTER_ACCESS_TOKEN ?? ''}`);
    lines.push(`TWITTER_ACCESS_SECRET=${values.TWITTER_ACCESS_SECRET ?? ''}`);
  }

  if (values.LINKEDIN_ACCESS_TOKEN) {
    lines.push('', '# LinkedIn');
    lines.push(`LINKEDIN_ACCESS_TOKEN=${values.LINKEDIN_ACCESS_TOKEN}`);
    lines.push(`LINKEDIN_USER_ID=${values.LINKEDIN_USER_ID ?? ''}`);
  }

  if (values.MEDIUM_TOKEN) {
    lines.push('', '# Medium');
    lines.push(`MEDIUM_TOKEN=${values.MEDIUM_TOKEN}`);
  }

  writeFileSync(envPath, lines.join('\n') + '\n', 'utf-8');
}

// ─── Claude Desktop config writer ────────────────────────────────────────────
function updateClaudeDesktopConfig(serverDir: string) {
  const configDir = join(homedir(), 'Library', 'Application Support', 'Claude');
  const configPath = join(configDir, 'claude_desktop_config.json');

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  let existing: Record<string, unknown> = {};
  if (existsSync(configPath)) {
    try {
      existing = JSON.parse(readFileSync(configPath, 'utf-8'));
    } catch {
      // use empty object
    }
  }

  const mcpServers = (existing.mcpServers as Record<string, unknown>) ?? {};
  mcpServers['retrospect-mcp'] = {
    command: 'node',
    args: [join(serverDir, 'dist', 'index.js')],
    env: {
      ENV_FILE: join(serverDir, '.env'),
    },
  };

  existing.mcpServers = mcpServers;
  writeFileSync(configPath, JSON.stringify(existing, null, 2) + '\n', 'utf-8');

  return configPath;
}

// ─── Main wizard ─────────────────────────────────────────────────────────────
async function main() {
  const serverDir = resolve(new URL('.', import.meta.url).pathname, '..');
  const envPath = join(serverDir, '.env');

  printHeader();

  // Check for existing config
  if (existsSync(envPath)) {
    console.log(`  ${yellow('!')} 기존 설정 파일이 있습니다: ${dim(envPath)}`);
    console.log('');
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  const env: Partial<EnvValues> = {};

  try {
    const TOTAL = 6;

    // ── Step 1: Claude API Key ───────────────────────────────────────────────
    printStep(1, TOTAL, 'Claude API Key (필수)');
    info('인사이트 추출에 Claude AI를 사용합니다.');
    info('API 키를 발급받으려면 console.anthropic.com → API Keys로 이동하세요.');
    console.log('');

    const openClaude = await rl.question(`  브라우저를 열까요? ${dim('[Y/n]')} `);
    if (openClaude.toLowerCase() !== 'n') {
      await openBrowser('https://console.anthropic.com/settings/keys');
      info('브라우저에서 API 키를 복사한 후 아래에 붙여넣으세요.');
    }

    while (!env.CLAUDE_API_KEY) {
      const key = await rl.question(`  API Key: `);
      if (key.trim().length < 10) {
        warn('올바른 API 키를 입력해주세요.');
        continue;
      }
      env.CLAUDE_API_KEY = key.trim();
    }
    ok(`API 키 저장: ${maskKey(env.CLAUDE_API_KEY)}`);

    // ── Step 2: Obsidian Vault ────────────────────────────────────────────────
    printStep(2, TOTAL, 'Obsidian 볼트 경로 (필수)');
    info('작업 로그가 저장될 Obsidian 볼트 폴더를 선택합니다.');

    const vaults = detectObsidianVaults();

    let vaultPath = '';
    if (vaults.length > 0) {
      console.log('');
      console.log('  발견된 Obsidian 볼트:');
      vaults.forEach((v, i) => console.log(`    ${cyan(`${i + 1}.`)} ${v}`));
      console.log(`    ${cyan(`${vaults.length + 1}.`)} 직접 입력`);
      console.log('');

      const choice = await rl.question(`  선택 ${dim(`[1-${vaults.length + 1}]`)}: `);
      const idx = parseInt(choice) - 1;

      if (idx >= 0 && idx < vaults.length) {
        vaultPath = vaults[idx];
      }
    }

    if (!vaultPath) {
      if (vaults.length === 0) {
        info('자동으로 감지된 볼트가 없습니다. 경로를 직접 입력해주세요.');
        info('예: /Users/minji/Documents/MyVault');
        console.log('');
      }
      while (!vaultPath) {
        const input = await rl.question('  볼트 경로: ');
        const trimmed = input.trim();
        if (!existsSync(trimmed)) {
          const create = await rl.question(`  해당 경로가 없습니다. 새로 만들까요? ${dim('[Y/n]')} `);
          if (create.toLowerCase() !== 'n') {
            mkdirSync(trimmed, { recursive: true });
            vaultPath = trimmed;
          }
        } else {
          vaultPath = trimmed;
        }
      }
    }

    env.OBSIDIAN_VAULT_PATH = vaultPath;
    env.DATABASE_PATH = join(serverDir, 'data', 'retrospect.db');
    ok(`Obsidian 볼트: ${vaultPath}`);

    // ── Step 3: Git repo ─────────────────────────────────────────────────────
    printStep(3, TOTAL, 'Git 기본 레포지토리 (선택)');
    info('analyze_git_commits 툴에서 기본으로 사용할 레포 경로입니다.');
    info('도구 호출 시 직접 지정할 수도 있으니 비워둬도 됩니다.');
    console.log('');

    const gitPath = await rl.question(`  Git 레포 경로 ${dim('(비우면 skip)')}: `);
    env.DEFAULT_GIT_REPO_PATH = gitPath.trim();

    if (env.DEFAULT_GIT_REPO_PATH) {
      ok(`Git 경로: ${env.DEFAULT_GIT_REPO_PATH}`);
    } else {
      info('Git 레포 설정 건너뜀');
    }

    // ── Step 4: Notion ────────────────────────────────────────────────────────
    printStep(4, TOTAL, 'Notion 연동 (선택)');
    info('작업 로그를 Obsidian과 함께 Notion에도 저장합니다.');
    console.log('');

    const useNotion = await rl.question(`  Notion 연동하시겠어요? ${dim('[y/N]')} `);
    if (useNotion.toLowerCase() === 'y') {
      info('Notion integration 토큰 발급 방법:');
      info('  1. notion.so/my-integrations 에서 새 인테그레이션 생성');
      info('  2. "Internal Integration Secret" 복사');
      info('  3. 연동할 Notion 페이지 → "..." → Connect to → 인테그레이션 선택');
      console.log('');

      const openNotion = await rl.question(`  브라우저를 열까요? ${dim('[Y/n]')} `);
      if (openNotion.toLowerCase() !== 'n') {
        await openBrowser('https://www.notion.so/my-integrations');
      }

      const notionToken = await rl.question('  Integration Secret (secret_...): ');
      if (notionToken.trim()) {
        env.NOTION_TOKEN = notionToken.trim();

        info('연동할 Notion 페이지 URL에서 ID를 복사하세요.');
        info('예: notion.so/My-Page-abc123def456 → abc123def456');
        const pageId = await rl.question('  Parent Page ID: ');
        env.NOTION_PARENT_PAGE_ID = pageId.trim();
        ok(`Notion 토큰: ${maskKey(env.NOTION_TOKEN)}`);
      } else {
        info('Notion 설정 건너뜀');
      }
    } else {
      info('Notion 설정 건너뜀');
    }

    // ── Step 5: SNS ───────────────────────────────────────────────────────────
    printStep(5, TOTAL, 'SNS 플랫폼 연동 (선택)');
    info('인사이트를 SNS에 발행할 때 필요합니다. 나중에 .env에서 추가 가능합니다.');
    console.log('');

    // Twitter/X
    const useTwitter = await rl.question(`  Twitter/X (Threads) 연동? ${dim('[y/N]')} `);
    if (useTwitter.toLowerCase() === 'y') {
      info('developer.twitter.com → Project → Keys and Tokens');
      const openTw = await rl.question(`  브라우저를 열까요? ${dim('[Y/n]')} `);
      if (openTw.toLowerCase() !== 'n') await openBrowser('https://developer.twitter.com/en/portal/projects-and-apps');
      env.TWITTER_BEARER_TOKEN = (await rl.question('  Bearer Token: ')).trim();
      env.TWITTER_API_KEY = (await rl.question('  API Key: ')).trim();
      env.TWITTER_API_SECRET = (await rl.question('  API Secret: ')).trim();
      env.TWITTER_ACCESS_TOKEN = (await rl.question('  Access Token: ')).trim();
      env.TWITTER_ACCESS_SECRET = (await rl.question('  Access Token Secret: ')).trim();
      if (env.TWITTER_BEARER_TOKEN) ok(`Twitter 설정 완료`);
    }

    // LinkedIn
    const useLinkedIn = await rl.question(`  LinkedIn 연동? ${dim('[y/N]')} `);
    if (useLinkedIn.toLowerCase() === 'y') {
      info('LinkedIn Developer Portal → 앱 생성 → OAuth 2.0 Access Token 발급');
      const openLI = await rl.question(`  브라우저를 열까요? ${dim('[Y/n]')} `);
      if (openLI.toLowerCase() !== 'n') await openBrowser('https://www.linkedin.com/developers/apps');
      env.LINKEDIN_ACCESS_TOKEN = (await rl.question('  Access Token: ')).trim();
      env.LINKEDIN_USER_ID = (await rl.question('  User ID (urn:li:person:...): ')).trim();
      if (env.LINKEDIN_ACCESS_TOKEN) ok('LinkedIn 설정 완료');
    }

    // Medium
    const useMedium = await rl.question(`  Medium 연동? ${dim('[y/N]')} `);
    if (useMedium.toLowerCase() === 'y') {
      info('medium.com/me/settings → Integration Tokens → Generate token');
      const openMed = await rl.question(`  브라우저를 열까요? ${dim('[Y/n]')} `);
      if (openMed.toLowerCase() !== 'n') await openBrowser('https://medium.com/me/settings/security');
      env.MEDIUM_TOKEN = (await rl.question('  Integration Token: ')).trim();
      if (env.MEDIUM_TOKEN) ok('Medium 설정 완료');
    }

    // ── Step 6: Write & finalize ──────────────────────────────────────────────
    printStep(6, TOTAL, '설정 저장');

    // Ensure data dir exists
    mkdirSync(join(serverDir, 'data'), { recursive: true });

    // Write .env
    writeEnvFile(env as EnvValues, envPath);
    ok(`.env 저장: ${envPath}`);

    // Update Claude Desktop config
    const desktopConfigPath = updateClaudeDesktopConfig(serverDir);
    ok(`Claude Desktop config 업데이트: ${desktopConfigPath}`);

    // Build
    console.log('');
    info('TypeScript 빌드 중...');
    try {
      await execAsync('npm run build', { cwd: serverDir });
      ok('빌드 완료');
    } catch (e: unknown) {
      warn(`빌드 실패: ${e instanceof Error ? e.message : String(e)}`);
      warn('수동으로 npm run build를 실행해주세요.');
    }

    // Done
    console.log('');
    console.log(bold(green('  ✓ 설정 완료!')));
    console.log('');
    console.log(`  ${bold('다음 단계:')}`);
    console.log(`    1. ${cyan('Claude Desktop을 재시작')}하면 retrospect-mcp가 자동 로드됩니다.`);
    console.log(`    2. Claude Desktop에서 ${bold('create_project')} 툴로 첫 프로젝트를 만들어보세요.`);
    console.log(`    3. 매일 ${bold('log_daily_work')} 툴로 작업을 기록하세요.`);
    console.log('');
    info(`설정 변경: ${envPath}`);
    info('재설정: npm run setup');
    console.log('');
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error(red(`\n  오류: ${err.message}`));
  process.exit(1);
});
